version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: medusa-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - medusa-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: ./Dockerfile
    container_name: medusa-auth-service
    restart: always
    env_file:
      - ./auth-service/.env
    ports:
      - "50051:50051"
    networks:
      - medusa-network
    depends_on:
      - mongodb

  core-service:
    build:
      context: ./core-service
      dockerfile: ./Dockerfile
    container_name: medusa-core-service
    restart: always
    depends_on:
      - auth-service
      - mongodb
    env_file:
      - ./core-service/.env
    ports:
      - "8080:8080"
    networks:
      - medusa-network

networks:
  medusa-network:
    driver: bridge

volumes:
  mongodb_data: